import com.example.shoppinggroceryapp.model.entities.products.Category

var categoryList = listOf(
    Category(categoryName="Fresh Fruits", parentCategoryName="Fruits & Vegetables", categoryDescription="All kinds of fresh fruits")
    ,
        Category(categoryName="Fresh Vegetables", parentCategoryName="Fruits & Vegetables", categoryDescription="All kinds of fresh vegetables")
        ,
            Category(categoryName="Organic Produce", parentCategoryName="Fruits & Vegetables", categoryDescription="Organic fruits and vegetables")
            ,
                Category(categoryName="Milk & Cream", parentCategoryName="Dairy & Eggs", categoryDescription="Different types of milk and cream")
                ,
                    Category(categoryName="Cheese", parentCategoryName="Dairy & Eggs", categoryDescription="Various types of cheese")
                    ,
                        Category(categoryName="Butter & Ghee", parentCategoryName="Dairy & Eggs", categoryDescription="Butter, ghee, and other dairy spreads")
                        ,
                            Category(categoryName="Eggs", parentCategoryName="Dairy & Eggs", categoryDescription="Fresh eggs")
                            ,
                                Category(categoryName="Bread", parentCategoryName="Bakery & Snacks", categoryDescription="Various types of bread")
                                ,
                                    Category(categoryName="Cakes & Pastries", parentCategoryName="Bakery & Snacks", categoryDescription="Cakes, pastries, and other baked goods")
                                    ,
                                        Category(categoryName="Cookies & Biscuits", parentCategoryName="Bakery & Snacks", categoryDescription="Cookies and biscuits")
                                        ,
                                            Category(categoryName="Chips & Crisps", parentCategoryName="Bakery & Snacks", categoryDescription="Packaged chips and crisps")
                                            ,
                                                Category(categoryName="Soft Drinks", parentCategoryName="Beverages", categoryDescription="Carbonated and non-carbonated soft drinks")
                                                ,
                                                    Category(categoryName="Juices", parentCategoryName="Beverages", categoryDescription="Various fruit and vegetable juices")

                                                    ,
                                                        Category(categoryName="Tea & Coffee", parentCategoryName="Beverages", categoryDescription="Different types of tea and coffee")
                                                        ,
                                                            Category(categoryName="Energy Drinks", parentCategoryName="Beverages", categoryDescription="Energy and sports drinks")
                                                            ,
                                                                Category(categoryName="Canned Goods", parentCategoryName="Packaged Foods", categoryDescription="Canned vegetables, fruits, and meats")
                                                                ,
                                                                    Category(categoryName="Frozen Meals", parentCategoryName="Packaged Foods", categoryDescription="Frozen ready-to-eat meals")
                                                                    ,
                                                                        Category(categoryName="Instant Foods", parentCategoryName="Packaged Foods", categoryDescription="Instant noodles, soups, and mixes")
                                                                        ,
                                                                            Category(categoryName="Ready-to-Eat Snacks", parentCategoryName="Packaged Foods", categoryDescription="Packaged snacks ready for consumption")
                                                                            ,
                                                                                Category(categoryName="Rice", parentCategoryName="Grains & Pulses", categoryDescription="Various types of rice")
                                                                                ,
                                                                                    Category(categoryName="Wheat & Flour", parentCategoryName="Grains & Pulses", categoryDescription="Wheat, flour, and other grains")
                                                                                    ,
                                                                                        Category(categoryName="Lentils", parentCategoryName="Grains & Pulses", categoryDescription="Different types of lentils")
                                                                                        ,
                                                                                            Category(categoryName="Beans", parentCategoryName="Grains & Pulses", categoryDescription="Various beans including kidney beans, chickpeas")
                                                                                            ,
                                                                                                Category(categoryName="Fresh Meat", parentCategoryName="Meat & Seafood", categoryDescription="Fresh cuts of meat")
                                                                                                ,
                                                                                                    Category(categoryName="Seafood", parentCategoryName="Meat & Seafood", categoryDescription="Various types of seafood")
                                                                                                    ,
                                                                                                        Category(categoryName="Frozen Meat", parentCategoryName="Meat & Seafood", categoryDescription="Frozen meat products")
                                                                                                        ,
                                                                                                            Category(categoryName="Processed Meat", parentCategoryName="Meat & Seafood", categoryDescription="Processed meats like sausages and cold cuts")
                                                                                                            ,
                                                                                                                Category(categoryName="Toiletries", parentCategoryName="Personal Care", categoryDescription="Items like soap, shampoo, and toothpaste")
                                                                                                                ,
                                                                                                                    Category(categoryName="Skincare", parentCategoryName="Personal Care", categoryDescription="Skincare products including creams and lotions")
                                                                                                                    ,
                                                                                                                        Category(categoryName="Haircare", parentCategoryName="Personal Care", categoryDescription="Haircare products like conditioners and treatments")
                                                                                                                        ,
                                                                                                                            Category(categoryName="Grooming", parentCategoryName="Personal Care", categoryDescription="Grooming tools and products")
                                                                                                                            ,
                                                                                                                                Category(categoryName="Cleaning Supplies", parentCategoryName="Household Items", categoryDescription="Cleaning agents and tools")
                                                                                                                                ,
                                                                                                                                    Category(categoryName="Kitchenware", parentCategoryName="Household Items", categoryDescription="Utensils, cookware, and other kitchen tools")
                                                                                                                                    ,
                                                                                                                                        Category(categoryName="Paper Products", parentCategoryName="Household Items", categoryDescription="Paper towels, toilet paper, and tissues")
                                                                                                                                        ,
                                                                                                                                            Category(categoryName="Laundry Products", parentCategoryName="Household Items", categoryDescription="Laundry detergents and fabric softeners")
                                                                                                                                            ,
                                                                                                                                                Category(categoryName="Medicines", parentCategoryName="Health & Wellness", categoryDescription="Over-the-counter medicines and health aids")
                                                                                                                                                ,
                                                                                                                                                    Category(categoryName="Vitamins & Supplements", parentCategoryName="Health & Wellness", categoryDescription="Vitamins and dietary supplements")
                                                                                                                                                    ,
                                                                                                                                                        Category(categoryName="Health Foods", parentCategoryName="Health & Wellness", categoryDescription="Foods with health benefits like protein bars and shakes")
                                                                                                                                                        ,
                                                                                                                                                            Category(categoryName="First Aid", parentCategoryName="Health & Wellness", categoryDescription="First aid supplies and medical kits")
                                                                                                                                                            ,
                                                                                                                                                                Category(categoryName="Diapers", parentCategoryName="Baby Care", categoryDescription="Various types of diapers")
                                                                                                                                                                ,
                                                                                                                                                                    Category(categoryName="Baby Food", parentCategoryName="Baby Care", categoryDescription="Packaged baby food and formula")
                                                                                                                                                                    ,
                                                                                                                                                                        Category(categoryName="Baby Toiletries", parentCategoryName="Baby Care", categoryDescription="Baby lotions, shampoos, and wipes")
                                                                                                                                                                        ,
                                                                                                                                                                            Category(categoryName="Baby Gear", parentCategoryName="Baby Care", categoryDescription="Baby accessories like bottles and pacifiers")
                                                                                                                                                                            ,
                                                                                                                                                                                Category(categoryName="Frozen Vegetables", parentCategoryName="Frozen Foods", categoryDescription="Frozen vegetables")
                                                                                                                                                                                ,
                                                                                                                                                                                    Category(categoryName="Frozen Fruits", parentCategoryName="Frozen Foods", categoryDescription="Frozen fruits")
                                                                                                                                                                                    ,
                                                                                                                                                                                        Category(categoryName="Frozen Desserts", parentCategoryName="Frozen Foods", categoryDescription="Frozen desserts and ice cream")
                                                                                                                                                                                        ,
                                                                                                                                                                                            Category(categoryName="Frozen Seafood", parentCategoryName="Frozen Foods", categoryDescription="Frozen seafood products")
                                                                                                                                                                                            ,
                                                                                                                                                                                                Category(categoryName="Spices", parentCategoryName="Condiments & Sauces", categoryDescription="Various spices and seasonings")
                                                                                                                                                                                                ,
                                                                                                                                                                                                    Category(categoryName="Cooking Sauces", parentCategoryName="Condiments & Sauces", categoryDescription="Sauces for cooking like soy sauce and tomato sauce")
                                                                                                                                                                                                    ,
                                                                                                                                                                                                        Category(categoryName="Ketchup & Mustard", parentCategoryName="Condiments & Sauces", categoryDescription="Condiments like ketchup and mustard")
                                                                                                                                                                                                        ,
                                                                                                                                                                                                            Category(categoryName="Pickles & Chutneys", parentCategoryName="Condiments & Sauces", categoryDescription="Various pickles and chutneys")
                                                                                                                                                                                                            ,
                                                                                                                                                                                                                Category(categoryName="Organic Fruits", parentCategoryName="Organic Products", categoryDescription="Organic fruits")
                                                                                                                                                                                                                ,
                                                                                                                                                                                                                    Category(categoryName="Organic Vegetables", parentCategoryName="Organic Products", categoryDescription="Organic vegetables")
                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                        Category(categoryName="Organic Grains", parentCategoryName="Organic Products", categoryDescription="Organic grains like rice and flour")
                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                            Category(categoryName="Organic Snacks", parentCategoryName="Organic Products", categoryDescription="Organic snack foods")
                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                Category(categoryName="Almonds", parentCategoryName="Dry Fruits & Nuts", categoryDescription="Almonds and almond products")
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                    Category(categoryName="Cashews", parentCategoryName="Dry Fruits & Nuts", categoryDescription="Cashews and cashew products")
                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                        Category(categoryName="Raisins", parentCategoryName="Dry Fruits & Nuts", categoryDescription="Raisins and other dried fruits")
                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                            Category(categoryName="Mixed Nuts", parentCategoryName="Dry Fruits & Nuts", categoryDescription="Mixed nuts and nut blends")
                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                Category(categoryName="Flour", parentCategoryName="Baking Needs", categoryDescription="Different types of flour for baking")
                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                    Category(categoryName="Sugar", parentCategoryName="Baking Needs", categoryDescription="Various types of sugar for baking")
                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                        Category(categoryName="Cake Mixes", parentCategoryName="Baking Needs", categoryDescription="Pre-packaged cake mixes and baking kits")
                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                            Category(categoryName="Vegetable Oil", parentCategoryName="Cooking Oils", categoryDescription="Vegetable oils for cooking")
                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                Category(categoryName="Olive Oil", parentCategoryName="Cooking Oils", categoryDescription="Olive oil for cooking and dressings")
                                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                    Category(categoryName="Sunflower Oil", parentCategoryName="Cooking Oils", categoryDescription="Sunflower oil for cooking")
                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                        Category(categoryName="Ghee", parentCategoryName="Cooking Oils", categoryDescription="Clarified butter used in cooking")
                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                            Category(categoryName="Cereals", parentCategoryName="Breakfast Foods", categoryDescription="Breakfast cereals including flakes and puffs")
                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                Category(categoryName="Oats", parentCategoryName="Breakfast Foods", categoryDescription="Oats and oatmeal products")
                                                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                                    Category(categoryName="Breakfast Bars", parentCategoryName="Breakfast Foods", categoryDescription="Granola bars and breakfast bars")
                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                        Category(categoryName="Pancake Mixes", parentCategoryName="Breakfast Foods", categoryDescription="Mixes for making pancakes and waffles")
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                            Category(categoryName="Italian", parentCategoryName="International Foods", categoryDescription="Italian foods including pasta and sauces")
                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                Category(categoryName="Chinese", parentCategoryName="International Foods", categoryDescription="Chinese foods including noodles and sauces")
                                                                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                                                    Category(categoryName="Mexican", parentCategoryName="International Foods", categoryDescription="Mexican foods including tortillas and salsas")
                                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                                        Category(categoryName="Indian", parentCategoryName="International Foods", categoryDescription="Indian foods including spices and ready-to-eat meals")
                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                            Category(categoryName="Chocolates", parentCategoryName="Sweets & Desserts", categoryDescription="Various types of chocolates")
                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                Category(categoryName="Candies", parentCategoryName="Sweets & Desserts", categoryDescription="Assorted candies and confectioneries")
                                                                                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                                                                    Category(categoryName="Cookies", parentCategoryName="Sweets & Desserts", categoryDescription="Various types of cookies")
                                                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                                                        Category(categoryName="Ice Creams", parentCategoryName="Sweets & Desserts", categoryDescription="Different flavors of ice cream")
                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                            Category(categoryName="Pet Food", parentCategoryName="Pet Supplies", categoryDescription="Food for various pets")
                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                Category(categoryName="Pet Toys", parentCategoryName="Pet Supplies", categoryDescription="Toys and play items for pets")
                                                                                                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                                                                                    Category(categoryName="Pet Grooming", parentCategoryName="Pet Supplies", categoryDescription="Grooming supplies for pets")
                                                                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                                                                        Category(categoryName="Pet Accessories", parentCategoryName="Pet Supplies", categoryDescription="Accessories like collars and leashes")
                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                            Category(categoryName="new 1", parentCategoryName="New", categoryDescription="")
                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                Category(categoryName="new 2", parentCategoryName="New", categoryDescription="")
                                                                                                                                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                                                                                                    Category(categoryName="new 5", parentCategoryName="Ne", categoryDescription="")
                                                                                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                                                                                        Category(categoryName="Baking Powder & Soda", parentCategoryName="Dairy & Eggs", categoryDescription="")
                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                            Category(categoryName="New Biscuits", parentCategoryName="Milk Bikis Biscuits", categoryDescription="")
                                                                                                                                                                                                                                                                                                                                                        )